services:
  webserver:
    image: "moodlehq/moodle-php-apache:${MOODLE_DOCKER_PHP_VERSION}"
    depends_on:
      - db
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html"
      - "${ASSETDIR}/web/apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
    environment:
      MOODLE_DOCKER_RUNNING: 1
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_BROWSER: firefox
      MOODLE_DOCKER_WEB_HOST: "${MOODLE_DOCKER_WEB_HOST}"
      MOODLE_DOCKER_TIMEOUT_FACTOR: "${MOODLE_DOCKER_TIMEOUT_FACTOR}"
    networks:
      - moodle_network
      - default
  exttests:
    image: moodlehq/moodle-exttests
    volumes:
      - "${ASSETDIR}/exttests/apache2_ports.conf:/etc/apache2/ports.conf"
      - "${ASSETDIR}/exttests/apache2.conf:/etc/apache2/sites-enabled/000-default.conf"
  selenium:
    image: "selenium/standalone-firefox${MOODLE_DOCKER_SELENIUM_SUFFIX:-}:${MOODLE_DOCKER_BROWSER_TAG}"
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html:ro"
  redis:
    image: redis:latest
    command: redis-server --bind 0.0.0.0 --protected-mode no
    volumes:
      - redis_data:/data
    networks:
      - moodle_network

  envoy:
    image: envoyproxy/envoy-contrib:v1.31-latest
    ports:
      - "6379:6379"
      - "9901:9901"
      - "10000:10000"
      - "22120:22120"
    volumes:
      - ./envoy.yml:/etc/envoy/envoy.yaml
    depends_on:
      - redis
    networks:
      - moodle_network

volumes:
  redis_data:

networks:
  moodle_network:
    driver: bridge
